### ISSUE TITLE
Pare down Docker

### ISSUE THREAD

**Issue by effigies** [nipreps/fmriprep-rodents#2]
What all packages do we need in Docker? The following are currently installed:

* [x] Pandoc
* [ ] FreeSurfer v6.0.1
* [x] FSL
* [x] AFNI
* [ ] Convert3D
* [ ] Connectome Workbench
* [ ] git-annex
* [x] ANTs
* [x] SVGO
* [x] bids-validator
* [x] ICA-AROMA

**Comment by eilidhmacnicol** [comment]
As far as the brain extraction workflow goes, ANTs is definitely needed for N4 correction and antsAI (at least for the moment). It's pretty light, and only depends on niworkflows and templateflow. I don't think bids-validator is needed for templateflow, and we don't currently require images to be in BIDS format, but to be comparable with other nipreps tools, we'd probably want to keep it. 

So far, I've been steering away from including FreeSurfer because cortical thickness pipelines generally aren't used for rodents (since there's no cortical folding) and it doesn't have any compatible templates, to my knowledge.

With the other packages, technically none of the others are required, but I don't know the fMRIPrep workflow well enough to know what is implemented at other stages of the pipeline beyond brain extraction (e.g. we've taken FSL out of the brain extraction pipeline, but I think it might be used at other stages). This is definitely true of the non-processing packages (e.g. Pandoc).

**Comment by eilidhmacnicol** [comment]
Okay - I've taken a second pass at this using the fMRIPrep docs.

The rest of the pipeline includes:
- FSL (FAST, motion correction, ICA-AROMA). I've got some code to do segmentation with ANTs Atropos, but FAST can be used with custom priors, although this requires a FLIRT transform from the subject to the priors' space. As for motion correction, I forget what came of the estimation of motion correction parameters but I'm not so sure that FSL is the preferred method. No issues with ICA-AROMA, since its data-driven.
- AFNI (slice time correction). No problems with this. I've used it for slice-time correction.
- Convert3D. I don't have any issue with this per se, I've used ITKSnap with rodent data before, but I can't find specifically what it is used for, and since we're not including surface-based methods, I can't think what else it would be used for. 
- Connectome Workbench - since this relies on FreeSurfer, I'd get rid of it. I don't know anyone using CIFTIs in rodents, but if they exist and want to change this, we can come back to it. For now, I don't think it's necessary.

With respect to the maintenance packages, I don't know what they're used for in fMRIPrep. We do generate .svg reports, so I've included SVGO. Since we don't have docs yet, I don't think Pandoc is necessary and I have no clue what git-annex is for.

**Comment by eilidhmacnicol** [comment]
I've been looking at the dockerfile again, and I notice that fmriprep uses ANTs 2.2, whereas nirodents uses ANTs 2.3.

This change was to access new parameters in `antsAI` rather than the regular `antsRegistration` call, but from personal experience, ants versioning can have quite a dramatic impact on results. 

Also, now having a better understanding of ICA-AROMA, I think it will take more work than I initially thought to modify it for rodent applications, but probably worth keeping just now until I can actually rule it out.
